# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Andrii Pashentsev's blog
email: andrey.pashentsev@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog by Andrii Pashentsev
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://andyps.github.io" # the base hostname & protocol for your site
github_username:  andyps
repository: andyps/andyps.github.io
timezone: UTC

# Build settings
markdown: kramdown

gems:
  - jekyll-seo-tag
  - jekyll-sitemap

